name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      DB_LIBRARY_DATABASE_ID: ${{ vars.DB_LIBRARY_DATABASE_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install
      - run: node --run=setup
      - run: node --run=build
