name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      PLAYWRIGHT_WEB_SERVER_COMMAND: 'node --run=start'
      RETROASSEMBLY_BUILD_TIME_VITE_DISABLE_FS_ACCESS_API: true
      RETROASSEMBLY_RUN_TIME_PORT: 5173
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install
      - run: node --run=setup
      - run: node --run=build
      - run: node --run=test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
