name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      VITE_ONEDRIVE_CLIENT_ID: ${{ vars.VITE_ONEDRIVE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      - run: node --run=build
